CREATE OR REPLACE PACKAGE APL_UTILS AS

  PROCEDURE DOWNLOAD_CUR_EXCH_RATE;
  PROCEDURE ACTION_CUR_EXCH_RATE;
  PROCEDURE LOAD_CUR_FROM_FILE;
  PROCEDURE ACTION_CUR_FROM_FILE;

END APL_UTILS;
/

CREATE OR REPLACE PACKAGE BODY APL_UTILS AS

  PROCEDURE DOWNLOAD_CUR_EXCH_RATE IS
  
  BEGIN
  
    DBMS_OUTPUT.PUT_LINE('Процедра заглушка, пока это процедра нечего не умеет :-) '||TO_CHAR(SYSDATE,'DD.MM.YYYY HH24:MI:SS'));
  
  END DOWNLOAD_CUR_EXCH_RATE;
  
PROCEDURE ACTION_CUR_EXCH_RATE IS
  
  BEGIN
  
    DBMS_OUTPUT.PUT_LINE('Процедра заглушка, пока это процедра нечего не умеет :-) '||TO_CHAR(SYSDATE,'DD.MM.YYYY HH24:MI:SS'));
  
  END ACTION_CUR_EXCH_RATE;
  
PROCEDURE LOAD_CUR_FROM_FILE IS
  
  BEGIN
  
    DBMS_OUTPUT.PUT_LINE('Процедра заглушка, пока это процедра нечего не умеет :-) '||TO_CHAR(SYSDATE,'DD.MM.YYYY HH24:MI:SS'));
  
  END LOAD_CUR_FROM_FILE;
  
PROCEDURE ACTION_CUR_FROM_FILE IS
  
  BEGIN
  
    DBMS_OUTPUT.PUT_LINE('Процедра заглушка, пока это процедра нечего не умеет :-) '||TO_CHAR(SYSDATE,'DD.MM.YYYY HH24:MI:SS'));
  
  END ACTION_CUR_FROM_FILE;

END APL_UTILS;
/
